tcp_addr: 0.0.0.0:19092

kafka:
  seed_peers:
    - kafka:9092

zoo_keeper:
  seed_peers:
    - zookeeper:2181

producer:
  channel_buffer_size: 4096
  shutdown_timeout: 30s

consumer:
  channel_buffer_size: 64
  long_polling_timeout: 3s
  registration_timeout: 20s
  backoff_timeout: 500ms
  rebalance_delay: 250ms
  offsets_commit_interval: 500ms
